/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Option } from "./components/tech-select/tech-select.typings";
export namespace Components {
    interface TechCafe {
    }
    interface TechSelect {
        "options": Option[];
        "value": string;
    }
}
declare global {
    interface HTMLTechCafeElement extends Components.TechCafe, HTMLStencilElement {
    }
    var HTMLTechCafeElement: {
        prototype: HTMLTechCafeElement;
        new (): HTMLTechCafeElement;
    };
    interface HTMLTechSelectElement extends Components.TechSelect, HTMLStencilElement {
    }
    var HTMLTechSelectElement: {
        prototype: HTMLTechSelectElement;
        new (): HTMLTechSelectElement;
    };
    interface HTMLElementTagNameMap {
        "tech-cafe": HTMLTechCafeElement;
        "tech-select": HTMLTechSelectElement;
    }
}
declare namespace LocalJSX {
    interface TechCafe {
    }
    interface TechSelect {
        "options"?: Option[];
        "value"?: string;
    }
    interface IntrinsicElements {
        "tech-cafe": TechCafe;
        "tech-select": TechSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tech-cafe": LocalJSX.TechCafe & JSXBase.HTMLAttributes<HTMLTechCafeElement>;
            "tech-select": LocalJSX.TechSelect & JSXBase.HTMLAttributes<HTMLTechSelectElement>;
        }
    }
}
